services:
  - type: web
    name: springboot-app
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/your-app.jar
    branch: main
    autoDeploy: true
